### ISSUE TITLE
Wireguard on QNAP

### ISSUE THREAD

**Issue by nickvin** [binhex/arch-qbittorrentvpn#132]
Having an issue on QNAP TS-451+ FW:5.0.0.1986 trying to run the container with Wireguard. Openvpn works fine.

```
2022-04-05 20:09:25,270 DEBG 'start-script' stderr output:
iptables-restore v1.8.7 (legacy): iptables-restore: unable to initialize table 'raw'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

2022-04-05 20:09:25,311 DEBG 'start-script' stderr output:
[#] ip -4 rule delete table 51820

2022-04-05 20:09:25,459 DEBG 'start-script' stderr output:
[#] ip -4 rule delete table main suppress_prefixlength 0

2022-04-05 20:09:25,661 DEBG 'start-script' stderr output:
[#] ip link delete dev wg0

2022-04-05 20:09:25,747 DEBG 'start-script' stdout output:
[warn] WireGuard interface failed to come 'up', exit code is '1'
```

Not sure if this problem is related, but a similar issue was raised for the linuxserver/docker-wireguard container: https://github.com/linuxserver/docker-wireguard/issues/42

I'm running the following docker-compose, but tried many iterations without any success:

```
version: "3.8"

services:
    qbittorrent:
        container_name: qbittorrent
        image: binhex/arch-qbittorrentvpn
        sysctls:
          - net.ipv4.conf.all.src_valid_mark=1
        privileged: true
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
        ports:
          - "6881:6881"
          - "6881:6881/udp"
          - "8112:8112"
          - "8118:8118"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /share/Docker/qbittorrent/config:/config
          - ${DOWNLOADS_DIR}:/data
        environment:
          VPN_ENABLED: ${VPN_ENABLED}
          VPN_USER: ${VPN_USER}
          VPN_PASS: ${VPN_PASS}
          VPN_PROV: ${VPN_PROV}
          VPN_CLIENT: ${VPN_CLIENT}
          STRICT_PORT_FORWARD: ${STRICT_PORT_FORWARD}
          ENABLE_PRIVOXY: ${ENABLE_PRIVOXY}
          LAN_NETWORK: ${LAN_NETWORK}
          NAME_SERVERS: ${NAME_SERVERS}
          VPN_INPUT_PORTS: ${VPN_INPUT_PORTS}
          VPN_OUTPUT_PORTS: ${VPN_OUTPUT_PORTS}
          DEBUG: ${DEBUG}
          UMASK: ${UMASK}
          PUID: ${PUID}
          PGID: ${PGID}
          WEBUI_PORT: 8112

        restart: unless-stopped
```

**Comment by KosherBacon** [comment]
I ran into this, and fixed it with the suggestion here https://github.com/linuxserver/docker-wireguard/issues/42#issuecomment-888930759

Still haven't fully gotten WireGuard to work (running into other problems) but hopefully this is still helpful.

**Comment by SteadBytes** [comment]
For me, `AllowedIPs` is being overwritten on container start to `AllowedIPs = 0.0.0.0/0` so changing that setting has no effect 🤔

**Comment by KosherBacon** [comment]
It sounds like you might be using PIA. If you're okay with losing port forwarding, you can generate the file, edit it to `AllowedIPs = 0.0.0.0/1, 128.0.0.0/1` and change `VPN_PROV` to `custom`. Upon restart it shouldn't overwrite the change (at least it didn't for me).

**Comment by ahurtaud** [comment]
@KosherBacon Have you completed your wireguard setup on qnap?
Everything seems connected on my side. But I dont seem to have access to anything..
no VPN, no ping to any IPs etc. 
Completely blocked. 
`wg show` displays somme connected info though...
```
[root@c5826c6b934f /]# wg show
interface: wg0
  public key: QvxxxxxxxxxxxxxxxxxxxxxxzgCicGXjWR4=
  private key: (hidden)
  listening port: 46906

peer: UrQiI9ISdPPzd4ARw1NHOPKKvKvxUhjwRjaI0JpJFgM=
  endpoint: 193.32.249.66:51820
  allowed ips: 0.0.0.0/1, 128.0.0.0/1
  transfer: 0 B received, 16.19 KiB sent
```

any idea?

**Comment by SteadBytes** [comment]
@KosherBacon sorry for the slow reply! Thank you for the suggestion, but I'm using Mullvad not PIA so already had `AllowedIPs=0.0.0.0/1, 128.0.0.0/1` and `VPN_PROV=custom`. It's interesting that yours isn't getting overwritten 🤔

**Comment by KosherBacon** [comment]
@ahurtaud I have unfortunately not gotten it to work.

WireGuard will "start" but won't complete a handshake. I just see RX as 0 bytes indefinitely, same as you.

**Comment by ahurtaud** [comment]
> @ahurtaud I have unfortunately not gotten it to work.
> 
> WireGuard will "start" but won't complete a handshake. I just see RX as 0 bytes indefinitely, same as you.

ok thanks for the info,
on my side I left the binhex image and went to the native qbittorent with bind network interface on the host.. :/

**Comment by nickvin** [comment]
Found the following container that has an implementation of WireGuard Go, which apparently solves the problem of running it on a NAS (QNAP, Synology, etc): [https://hotio.dev/containers/qbittorrent/](https://hotio.dev/containers/qbittorrent/)

Unfortunately, it doesn't seem to have any port forwarding capabilities.

**Comment by KosherBacon** [comment]
I've hopefully figured out a workaround for now. After much digging, it looks like on QNAP the container is trying to route packets to the wireguard endpoint over the wireguard tunnel, so those packets never arrive.

For example, if the VPN endpoint is `200.200.200.200:51820`, and using `AllowedIPs = 128.0.0.0/1, 0.0.0.0/1` the traffic never seems to arrive. I only noticed the difference here because I accidentally set `AllowedIPs = 127.0.0.0/1, 0.0.0.0/1`. An innocuous error, but my wireguard tunnel came up for the first time, though most of my traffic was failing.

What was strange was that pinging `1.1.1.1` and even `curl ipinfo.io` (`34.x.x.x`) worked. But when I "corrected" my wireguard config, it never seemed to work. I then found [this](https://www.reddit.com/r/WireGuard/comments/emjgp0/comment/fdqjr9w/?utm_source=share&utm_medium=web2x&context=3) Reddit link. The code there generated a wireguard `AllowedIPs` list where I could exempt specific IPs.

(modified the exclude list slightly)

```
from ipaddress import ip_network

start = '0.0.0.0/0'
exclude = ['200.200.200.200']

result = [ip_network(start)]
for x in exclude:
    n = ip_network(x)
    new = []
    for y in result:
        if y.overlaps(n):
            new.extend(y.address_exclude(n))
        else:
            new.append(y)
    result = new

print(','.join(str(x) for x in sorted(result)))
```

And I just exempted only the IP of my wireguard endpoint. Using the output from this script in the wireguard `AllowedIPs` field got it working.

As far as I can tell, everything that should be going through the tunnel, is. Maybe there's something that can be tweaked in the container's `iptables`? Or maybe this is wildly wrong... But it did seem to work.
