### ISSUE TITLE
unraid issues mover not moving 

### ISSUE THREAD

**Issue by lawrence1986101** [binhex/arch-qbittorrentvpn#225]
### qBittorrent & operating system versions

i on the latest QB on unraid v.4.6.3

### What is the problem?

mover isn't moving downloads from cache to array 

### Steps to reproduce

Simple really: if I have my downloads going to Downloads, then Sonarr and radarr would pick them up, and from downloads, it would get moved to the array of downloads from the cache drive. How would I get them to move it? Stop QB, hit the mover, then they would move, then start QB. or you can pause the torrent that stuck in the cache drive than hit mover and it would move the files and unpause the torrent 

### Additional context

![427023323_927479912341386_6523861911629449121_n](https://github.com/binhex/arch-qbittorrentvpn/assets/79987458/1b82a4e2-b3ff-4ae5-b35c-98d497f472fd)
[qbittorrent.log](https://github.com/binhex/arch-qbittorrentvpn/files/14452692/qbittorrent.log)

You can see in the background of this photo that it's my cache drive. I was going to try and manually move the file, but as you see, it's already there, so it's like a ghost file. but for some reason it's not really moving over until you stop QB. It's like a ghost file or something; I don't know what to call it.

**Comment by lawrence1986101** [comment]
You all need to change this sh*t back to how it was because I refuse to use this program. 

https://trash-guides.info/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent/?fbclid=IwAR0PFZ4UCIcY6J8WtJvcxN7k5g4-8GYYDQAAo6ElBZ9t7Ee6DmQZm8eOC8Y

Your program is now trash. I'm not going to do any of that. I just paid $200 for NZB. I can't put a price on convenience or something that works how it is intended to work. I will not be taking extra steps to get this shitty ass docker to work.

**Comment by binhex** [comment]
Firstly i am a single developer on my own doing this shit for **free**, so PLEASE calm the fuck down or piss off, the choice is yours.

With that out of the way let's address the issue, so due to the way torrents work mover will not be able to move a file that is in use, as rightly stated by trash guide linked above, so either wait until the torrent has finished seeding so it can be moved, or use the script linked in trash's guide (not used it myself).

Keep in mind i do not develop qBittorrent or UNRAID, so i have ZERO influence on mover or the way in which qBittorrent works, if you had a previous version that used to work then you could attempt rollback by specifying the tag version, see Q5:- https://github.com/binhex/documentation/blob/master/docker/faq/unraid.md
