### ISSUE TITLE
Trouble stopping or killing the container 

### ISSUE THREAD

**Issue by JackBird15** [binhex/arch-qbittorrentvpn#245]
Whenever i try to stop or kill the container, it doesn't work. This is because after a prolonged time with the container on, it just stops downloading, and just needs a reboot to sort itself out. However, not being able to stop and start the container makes it really hard as it means I have to reboot my whole system, rather than just the docker container. I'm not sure what logs to post, so would appreciate any guidance on my next steps - please be nice :))

**Comment by henriquevcosta** [comment]
I'd try to investigate why it stops downloading after a while rather than why it needs a reboot, and logs should have some info about that (and you can launch the container with DEBUG=true) to hopefully get some more info.
One thing that is often overlooked for setups that are running for a long time is proper docker log configuration to get rotation and good management of host resources, I'd make sure to have the daemon configured with the `local` logging driver (and recreate the container to make sure it's used) - see this as an example https://signoz.io/blog/docker-log-rotation/

**Comment by JackBird15** [comment]
Thank you! i havent been able to try this yet but I absolutely will! However I will just say that even if I did want to do this, I'm going to have to hard stop my docker VM as qbittorentVPN refuses to close, hopefully the debug helps me out! and I'll post it here when I get some good results :) thank you!

**Comment by JackBird15** [comment]
This turned out to be my fault! my truenas scale didn't have full internet rights, and when qbittorent changed VPN it caused a bit of a mess, however this was Truenas issue/user error, and not qbittorent.
