### ISSUE TITLE
Container suddenly having socket errors

### ISSUE THREAD

**Issue by LHOswald65** [binhex/arch-qbittorrentvpn#252]
![Screenshot_20240705-132429](https://github.com/binhex/arch-qbittorrentvpn/assets/173641022/8f96380f-78aa-4626-b5b0-2d791631d1b8)

Was fine last night until the container was updated

**Comment by binhex** [comment]
It's fixed in the latest image, pull latest

**Comment by LHOswald65** [comment]
When I pull :latest image I get the errors. Reverting to :4.6.5-1-05 fixes
the issue though

**Comment by DaBenjamins** [comment]
I also get these errors on latest, 4.6.5-1-06, and 4.6.5-1-07

**Comment by Coalbus** [comment]
Latest image fixed this for me. Thanks!

**Comment by groot-stuff** [comment]
On unRaid 6.12.6, pulling _binhex/arch-qbittorrentvpn:4.6.5-1-07_ fixes the issue, however I had to use that tag specifically to get it to pull down.
Using the Repository values below results in errors from log screenshot above
- binhex/arch-qbittorrentvpn:latest
- binhex/arch-qbittorrentvpn (default in unRaid docker template)

Also had same issue with binhex-delugevpn on unRaid 6.12.6 and had to specify _binhex/arch-delugevpn:2.1.1-6-05_ (rather than :latest or no tag) to get it pulled down correctly.

**Comment by binhex** [comment]
@groot-stuff that will be due to docker not refreshing the image, if you want to switch back to latest then do the following in unraid:-

1. login to unraid web ui
2. go to docker tab
3. left click container and select 'edit' and switch back repository to tag 'latest' and apply
4. toggle switch top right to 'advanced view' on main docker screen (not edit screen)
5. click on 'force update' for the container, this will force a refresh of tagged image latest
6. check logs for errors.
