### ISSUE TITLE
PIA: looses connection every 24 hours

### ISSUE THREAD

**Issue by gurabli** [binhex/arch-qbittorrentvpn#32]
I had fully working system for a long time.
Now, for few weeks, the connection to PIA brakes in a time of 24 hours or less. I can access qbit UI, but nothing is downloading. Need to restart container and zhan everything runs just fine. Any idea why?
Don't have the logs now, but it looks that can't resolve DNS after a while.

Anybody else having this issue with PIA?

**Comment by gaiacanon** [comment]
Mine stopped downloading anything at all starting last night. Several restarts of the containers and still nothing.

My torrent shows 7 seeds, but I'm not connected to any

**Comment by KENNNNNT** [comment]
@mtalexan I am also using ProtonVPN, I have the p2p .opvn files (switz, sweeden etc) in my appdata\openvpn, however cannot get the container to run.  When I was using PIA it was working fine, after adding the AES-256-CBC string to the .opvn files, however the proton files have this value included yet the container logs still errors on it, and fails to run. Any advice?

**Comment by mtalexan** [comment]
I forked this and the arch-qbittorrentvpn repos about a treat ago to implement support for multiple remote lines in the ovpn files, something binged decided to implement differently about 2 months ago rather than using my pull requests, so I've been on that for a while. As of my fork, the AES-256-CBC line in the Proton VPN ovpn  was working just fine.
That suggests it could be some other change binhex made, or it could be a result of a newer openvpn client version.

I'd suggest you start by getting a pristine copy of the ovpn file, copy it into the location the container uses, and after starting the container, diff the two files. The ovpn file semi- silently modified in binhex's version to strip unsupported lines and modify others. It would be worth checking to see what the differences are from the original.
