### ISSUE TITLE
OVPN files with multiple remotes not handled properly

### ISSUE THREAD

**Issue by mtalexan** [binhex/arch-qbittorrentvpn#41]
Some VPN providers (e.g. ProtonVPN) provide ovpn files that include a list of multiple remotes.

For example:
```
remote 185.159.158.133 443
remote 185.159.158.133 5995
remote 185.159.158.133 8443
remote 185.159.158.137 443
remote 185.159.158.137 5995
remote 185.159.158.137 8443
remote 185.159.158.141 443
remote 185.159.158.141 5995
remote 185.159.158.141 8443
remote 185.159.158.142 443
remote 185.159.158.142 5995
remote 185.159.158.142 8443
```

The current logic attempts to identify a `remote` line and converts a potential server name to an IP address.
It appears it currently parses all of the lines, but only writes back the results for the first line.  In a case like the one above, only the line
```
remote 185.159.158.133 443
```
is written back to the file and the rest are removed.  The reason an ovpn file would include a list of remotes is for the case where one of the listed remotes isn't available and a fallback should be used.  By eliminating all but one line, it makes it very likely that the VPN will fail to connect

**Comment by mtalexan** [comment]
When attempting to reproduce #40, I also discovered that only the port from the first `remote` line is added to the iptable exceptions.

**Comment by binhex** [comment]
> The reason an ovpn file would include a list of remotes is for the case where one of the listed remotes isn't available and a fallback should be used. By eliminating all but one line, it makes it very likely that the VPN will fail to connect

i dont disagree with any of the above, i am fully aware of the reason for having multiple remote lines in an ovpn file. 

when i first coded up the vpn docker image i produce i ran into complexity around multiple remote lines and the decision was taken at that time to simplify things by writing back a single remote line back and removing other remote lines, this isnt such a problem for vpn providers that use multiple A record entries in dns as it still gives you fallback servers to connect to (all resolved ip's are written to hosts file).

for the vpn provider you are connecting to however its a bit more of an issue as they hard code ip addresses in their ovpn file so i see why this is a problem for you.

so the complexity of the issue is still there so i will have to take another look at the issue and see how difficult this is really going to be, so its not going to be a change that will happen soon.

**Comment by mtalexan** [comment]
You can assign this issue to me if you'd like.  I've already forked the binhex/arch-int-openvpn and binhex/arch-qbittorrentvpn to make changes (in a backwards compatible way for the arch-int-openvpn) to allow a list of `remote`s that might be server names or IP addresses (or a mix).

Do you want me to create a matching issue for this on arch-int-openvpn also?

**Comment by binhex** [comment]
this is now correctly handled, see Q20 for examples on how to use this:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
