### ISSUE TITLE
LAN_NETWORK enviroment variable does not have any effect.

### ISSUE THREAD

**Issue by Eagleman7** [binhex/arch-qbittorrentvpn#68]
I tried starting qbittorrentvpn for the first time today. I was suprised by the login page because I've set the following enviromental variable:

LAN_NETWORK=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8

However after many tries, with and without comma's I kept getting the login page.

Only after adding above subnets to the webinterface and enabling "Bypass authentication for clients in whitelisted IP subnets" I got around the login page.

![image](https://user-images.githubusercontent.com/4787591/101402525-26328780-38d4-11eb-91fa-580508e0322b.png)

**Comment by binhex** [comment]
it does have effect, it will add in iptables to permit you to be able to access the webui from your lan, which obviously is working for you as you can access the qbittorrent web ui. As for unable to login, the bypass authentication list is not the answer, the underlying issue is something else, i have no whitelist specified and i can login fine, please do the following:- 
https://github.com/binhex/documentation/blob/master/docker/faq/help.md

**Comment by Eagleman7** [comment]
I was able to login with the default credentials. However I was under the impression that the LAN_NETWORK would set the Bypass authentication for clients in whitelisted IP subnets in qBitotorrent. However it seems to only set the firewall.

**Comment by Eagleman7** [comment]
Did some more research. When I run traefik as reverse proxy in front of qbittorrent the LAN_NETWORK options are not needed at all. I've whitelisted a non-existing network and was still able to access qbittorrent through traefik.
